# Generated by Django 4.2.7 on 2023-11-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='weather_forcast',
            field=models.JSONField(blank=True),
        ),
    ]
