# Generated by Django 4.2.7 on 2023-11-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='external_user_id',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
