# Generated by Django 4.2.7 on 2023-11-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelservice', '0002_trip_trip_name_alter_trip_weather_forcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.UUIDField(default='00000000-0000-0000-0000-000000000000', primary_key=True, serialize=False, unique=True),
        ),
    ]
