# Generated by Django 4.2.7 on 2023-11-23 23:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('travelservice', '0002_alter_customuser_external_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='external_user_id',
            field=models.UUIDField(default=uuid.UUID('18983ecf-870d-44c2-bf9f-d53b0d370a05'), editable=False, null=True, unique=True),
        ),
    ]
