# Generated by Django 4.2.7 on 2023-11-23 23:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('travelservice', '0003_alter_customuser_external_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='external_user_id',
            field=models.UUIDField(default=uuid.UUID('d3159726-652e-4c05-b969-0e7cc9de2655'), editable=False, unique=True),
        ),
    ]
