# Generated by Django 4.2.7 on 2023-11-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelservice', '0004_alter_customuser_external_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='external_user_id',
            field=models.UUIDField(default='e4d2ddbe-3004-4d71-8c59-d6678d9c0ae4', editable=False, unique=True),
        ),
    ]
