# Generated by Django 4.2.7 on 2023-11-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelservice', '0004_alter_trip_weather_forcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='weather_forcast',
            field=models.TextField(blank=True, default=''),
        ),
    ]
