# Generated by Django 4.2.7 on 2023-11-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelservice', '0007_alter_trip_weather_forcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
