# Generated by Django 4.2.7 on 2023-11-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelservice', '0008_trip_lat_trip_lon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='lon',
            new_name='longitude',
        ),
    ]
