# Generated by Django 4.2.7 on 2023-11-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelservice', '0009_rename_lat_trip_latitude_rename_lon_trip_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
