# Generated by Django 4.2.7 on 2023-11-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelservice', '0010_alter_trip_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='interests',
            field=models.IntegerField(default=0),
        ),
    ]
