# Generated by Django 4.2.7 on 2023-12-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelservice', '0011_trip_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='users_interested',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
