# Generated by Django 4.2.7 on 2023-12-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelservice', '0012_trip_users_interested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='users_interested',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
