# Generated by Django 4.2.7 on 2023-12-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelservice', '0013_alter_trip_users_interested'),
    ]

    operations = [
        migrations.CreateModel(
            name='UUIDCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
            ],
        ),
    ]
